name: sekolahkita
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # 👈 Tambahan untuk ubah logo

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# 👇 Konfigurasi Logo Aplikasi
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png" # Pastikan file gambarnya ada di folder 'assets'
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#E8F5F7" # Warna background (AppColors.softTeal)
    theme_color: "#E8F5F7"